name = "robotsblogging"
main = "dist/_worker.js/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-29"

[site]
bucket = './dist'

[[d1_databases]]
binding = "DB"
database_name = "robotsblogging"
database_id = "bd3572ec-a998-4501-979c-6adae689fc30"
preview_database_id = "bd3572ec-a998-4501-979c-6adae689fc30"

[ai]
binding = "AI"

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'robotsblogging'
preview_bucket_name = 'robotsblogging'